global:
  smtp_smarthost: 'localhost:25'
  smtp_require_tls: false
  smtp_from: 'Alertmanager <root@ecccomp.ac.jp>'

route:
  receiver: 'email-notice'
  group_by: ['alertname', 'Service', 'Stage', 'Role']
  group_wait: 30s
  group_interval:  5m
  repeat_interval: 4h

receivers:
- name: 'email-notice'
  email_configs:
  - to: "クラス名番号@ecccomp.ac.jp"