/*
データベース構築　DDL文 
クラス：SK2A03
制作者：文家俊
作成日：2023/06/02
*/

/*---------------テーブル作成----------------------*/
-- 値引区分

CREATE TABLE DISCOUNT(
	DISC_CLASS   INT(1),
	DISC_METHOD  VARCHAR(10) NOT NULL,
	PRIMARY KEY(DISC_CLASS)
);
	
-- 引渡区分

CREATE TABLE DELIVERY(
	DELI_CLASS   INT(1),
	DELI_METHOD  VARCHAR(10) NOT NULL,
	PRIMARY KEY(DELI_CLASS)
);

-- 支払区分

CREATE TABLE PAYMENT(
	PAY_CLASS   INT(1),
	PAY_METHOD  VARCHAR(10) NOT NULL,
	PRIMARY KEY(PAY_CLASS)
);

-- キャンペーン表

CREATE TABLE CAMPAIGN(
	CAMP_CODE	CHAR(4),
	EXP_TEXT	VARCHAR(256) NOT NULL,
	START_DATE	DATE NOT NULL,
	END_DATE	DATE NOT NULL,
	COUPON_NAME	VARCHAR(50) NOT NULL,
	DISC_CLASS	INT(1) NOT NULL,
	DISC_VALUE	INT(4) NOT NULL,
	USE_PERIOD	DATE NOT NULL,
	VALID_COUNT	INT(1) NOT NULL,
	APPLY_MONEY	INT(6) NOT NULL,
	PRIMARY KEY(CAMP_CODE),
	FOREIGN KEY(DISC_CLASS) REFERENCES DISCOUNT(DISC_CLASS)
);

-- 顧客表

CREATE TABLE USER(
	USER_NO		INT(11) AUTO_INCREMENT,
	UNAME		VARCHAR(20) NOT NULL,
	RUBY		VARCHAR(60) NOT NULL,
	MAIL		VARCHAR(256) NOT NULL,
	PASSWORD	VARCHAR(64) NOT NULL,
	TEL		VARCHAR(10) NOT NULL,
	CARD_NO		CHAR(16),
	PRIMARY KEY(USER_NO),
	UNIQUE(MAIL),
	UNIQUE(TEL),
	UNIQUE(CARD_NO)
);

-- お届け先表

CREATE TABLE DELIADDRESS(
	USER_NO		INT(11),
	DELI_NO		INT(1),
	POST_NO		INT(7) NOT NULL,
	ADDRESS		VARCHAR(100) NOT NULL,
	PRIMARY KEY(USER_NO,DELI_NO)
);

-- 保有クーポン表

CREATE TABLE OWNEDCP(
	USER_NO		INT(11),
	CAMP_CODE	CHAR(4),
	COUPON_NAME	VARCHAR(50),
	DISC_CLASS	INT(1),
	DISC_VALUE	INT(4),
	USE_PERIOD	DATE,
	REMAIN_COUNT	INT(1),
	PRIMARY KEY(USER_NO, CAMP_CODE),
	FOREIGN KEY(DISC_CLASS) REFERENCES CAMPAIGN(DISC_CLASS),
	FOREIGN KEY(DISC_CLASS) REFERENCES DISCOUNT(DISC_CLASS),
	FOREIGN KEY (`USER_NO`) REFERENCES `USER` (`USER_NO`)
);

-- 受注ヘッダ表

CREATE TABLE ORDERHEADER(
	ODR_NO			INT(11) AUTO_INCREMENT,
	ODR_DATE		DATETIME NOT NULL DEFAULT NOW(),
	EMP_NO			CHAR(5),
	STORE_NO		CHAR(3),
	USER_NO			INT(11),
	UNAME			VARCHAR(20),
	TEL			VARCHAR(10),
	POST_NO			INT(7),
	ADDRESS			VARCHAR(100),
	CAMP_CODE		CHAR(4),
	COUPON_NAME		VARCHAR(50),
	USE_PERIOD		DATE,
	DELI_CLASS		INT(1),
	PAY_CLASS		INT(1),
	TAX			INT(2) NOT NULL,
	APPLY_CAMP_CODE		CHAR(4),
	APPLY_COUPON_NAME	VARCHAR(50),
	APPLY_USE_PERIOD	DATE,
	APPLY_VALID_COUNT	INT(1),
	PRIMARY KEY(ODR_NO),
	FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
	FOREIGN KEY(STORE_NO) REFERENCES STORE(STORE_NO),
	FOREIGN KEY(USER_NO) REFERENCES USER(USER_NO),
	FOREIGN KEY(DELI_CLASS) REFERENCES DELIVERY(DELI_CLASS),
	FOREIGN KEY(PAY_CLASS) REFERENCES PAYMENT(PAY_CLASS),
	FOREIGN KEY(APPLY_CAMP_CODE) REFERENCES CAMPAIGN(CAMP_CODE),
	FOREIGN KEY (`ODR_NO`) REFERENCES `ORDERDETAIL` (`ODR_NO`)

);

-- 受注明細表

CREATE TABLE ORDERDETAIL(
	ODR_NO		CHAR(4),
	DET_NO		INT(2),
	PRODUCT_NO	CHAR(4),
	PNAME		VARCHAR(50),
	CATEGORY	VARCHAR(4),
	SIZE		CHAR(4),
	UNIT_PRICE	INT(5),
	QTY		INT(2),
	PRIMARY KEY(ODR_NO, DET_NO),
	FOREIGN KEY(PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO),
	FOREIGN KEY (`PRODUCT_NO`) REFERENCES `PRODUCT` (`PRODUCT_NO`)
);

/*---------------------データ挿入---------------------------*/
-- 区分データ登録

INSERT INTO DISCOUNT(DISC_CLASS, DISC_METHOD)
VALUES(1,'金額値引き'),(2,'％値引き');

INSERT INTO DELIVERY(DELI_CLASS, DELI_METHOD)
VALUES(1,'受取'),(2,'配達');

INSERT INTO PAYMENT(PAY_CLASS, PAY_METHOD)
VALUES(1,'現金'),(2,'カード');

-- データ確定

SELECT DISC_CLASS AS '区分', DISC_METHOD AS '方法' FROM DISCOUNT
UNION
SELECT * FROM DELIVERY
UNION
SELECT * FROM PAYMENT;

