/*
データベース演習II 7週目
クラス：SK2A03
制作者：文家俊
作成日：2023/06/02
*/

--問８：addStudb.sqlを実行してデータベースの構築をしてください。
--※source文を使用してください。

Source addStudb.sql;

-- 問９：作成した全てのテーブルの列構造を確認してください。

DESCRIBE STUDBY2.DISCOUNT;
DESCRIBE STUDBY2.DELIVERY;
DESCRIBE STUDBY2.PAYMENT;
DESCRIBE STUDBY2.CAMPAIGN;
DESCRIBE STUDBY2.USER;
DESCRIBE STUDBY2.DELIADDRESS;
DESCRIBE STUDBY2.OWNEDCP;
DESCRIBE STUDBY2.ORDERHEADER;
DESCRIBE STUDBY2.ORDERDETAIL;


